# Generated by Django 2.1.5 on 2019-03-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='licenseOfOrganisation',
            field=models.FileField(blank=True, upload_to='organisationlicense/'),
        ),
        migrations.AlterField(
            model_name='pharamcy',
            name='licenseOfPharmacist',
            field=models.FileField(blank=True, upload_to='pharmacistlicense/'),
        ),
    ]
