# Generated by Django 2.1.5 on 2019-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0002_auto_20190303_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='licenseNumber',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='pharamcy',
            name='licenseNumber',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='latitude',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='licenseOfOrganisation',
            field=models.FileField(blank=True, null=True, upload_to='organisationlicense/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='longitude',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pharamcy',
            name='latitude',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='pharamcy',
            name='licenseOfPharmacist',
            field=models.FileField(blank=True, null=True, upload_to='pharmacistlicense/'),
        ),
        migrations.AlterField(
            model_name='pharamcy',
            name='longitude',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
