# Generated by Django 2.1.5 on 2019-03-02 06:19

from django.db import migrations, models
import django.db.models.deletion
import medex.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.IntegerField()),
                ('pricePerTablet', models.DecimalField(decimal_places=10, default=0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MedicineOfUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('creditForMedicine', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expiryDate', models.DateField()),
                ('medicinePicture', models.ImageField(upload_to=medex.models.user_directory_path)),
                ('expiryPicture', models.ImageField(upload_to=medex.models.get_user_image_folder)),
                ('quantityOfMedicine', models.IntegerField()),
                ('isSoldByPharmacist', models.BooleanField(default=False)),
                ('isAcceptedByPharmacist', models.BooleanField(default=False)),
                ('isRequested', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medex.Medicine')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
