# Generated by Django 2.1.5 on 2019-03-02 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineofuser',
            name='pharmacist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='useraccounts.Pharamcy'),
        ),
        migrations.AddField(
            model_name='medicineofuser',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicineOfUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
