# Generated by Django 2.1.5 on 2019-03-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medex', '0002_auto_20190302_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineofuser',
            name='creditForMedicine',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True),
        ),
    ]
