# Generated by Django 2.1.5 on 2019-03-03 01:08

from django.db import migrations, models
import medex.models


class Migration(migrations.Migration):

    dependencies = [
        ('medex', '0003_auto_20190302_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedMedicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('requests', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=50)),
                ('isAdded', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='medicineofuser',
            name='expiryPicture',
            field=models.ImageField(blank=True, upload_to=medex.models.get_user_image_folder),
        ),
        migrations.AlterField(
            model_name='medicineofuser',
            name='medicinePicture',
            field=models.ImageField(blank=True, upload_to=medex.models.user_directory_path),
        ),
    ]
