# Generated by Django 2.1.5 on 2019-03-03 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medex', '0004_auto_20190303_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedmedicines',
            old_name='isAdded',
            new_name='isAccepted',
        ),
    ]
