# Generated by Django 2.1.5 on 2019-03-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medex', '0005_auto_20190303_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedmedicines',
            old_name='requests',
            new_name='medicineRequested',
        ),
    ]
